version: '3.8'

services:
  python_api:
    build:
      context: ./configs/python
      dockerfile: Dockerfile
    container_name: python_api
    ports:
      - "8000:8000"
    networks:
      - app-network

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"  # Puertos por defecto de MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops_app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
