version: '3.8'

services:
  python_api:
    build:
      context: ./configs/python
      dockerfile: Dockerfile
    container_name: python_api
    ports:
      - "8000:8000"
    networks:
      - app-network

  mysql_db:
    build:
      context: ./configs/mysql
      dockerfile: Dockerfile
    container_name: mysql_db
    ports:
      - "4400:3306"  # Puertos por defecto de MySQL redirigido al 4400
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops_app
    networks:
      - app-network

  unit_tests:
    build:
      context: ./configs/unit_tests
      dockerfile: Dockerfile
    container_name: unit_tests_python_api
    
    networks:
      - app-network
      
volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge
